"""CRUD helpers for keyset persistence (NUT-01/02).

All functions accept an ``AsyncSession`` and perform async SQLAlchemy queries.
"""

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from cashu_mint.crypto.ec import point_to_bytes, privkey_from_bytes, privkey_to_pubkey
from cashu_mint.db.keyset_models import Keyset, KeysetKey


async def get_all_keysets(db: AsyncSession) -> list[Keyset]:
    """Return all keysets ordered by creation time (newest first)."""
    result = await db.execute(
        select(Keyset).order_by(Keyset.created_at.desc())
    )
    return list(result.scalars().all())


async def get_active_keysets(db: AsyncSession) -> list[Keyset]:
    """Return active keysets ordered by creation time (newest first)."""
    result = await db.execute(
        select(Keyset)
        .where(Keyset.active.is_(True))
        .order_by(Keyset.created_at.desc())
    )
    return list(result.scalars().all())


async def get_keyset_by_id(db: AsyncSession, keyset_id: str) -> Keyset | None:
    """Return the keyset with the given ID, or None if not found."""
    result = await db.execute(select(Keyset).where(Keyset.id == keyset_id))
    return result.scalar_one_or_none()


async def get_keyset_public_keys(
    db: AsyncSession, keyset_id: str
) -> dict[int, str]:
    """Return a {denomination: compressed_pubkey_hex} mapping for a keyset.

    Public keys are re-derived from stored private keys on the fly so that
    only private keys need to be persisted, and the public keys served via the
    API are always consistent with the private keys used for signing.

    Private key bytes are never included in the return value.
    """
    result = await db.execute(
        select(KeysetKey)
        .where(KeysetKey.keyset_id == keyset_id)
        .order_by(KeysetKey.amount)
    )
    rows = result.scalars().all()
    pub_keys: dict[int, str] = {}
    for row in rows:
        k = privkey_from_bytes(bytes.fromhex(row.private_key))
        pub_keys[row.amount] = point_to_bytes(privkey_to_pubkey(k)).hex()
    return pub_keys


async def save_keyset(db: AsyncSession, keyset_data: dict) -> Keyset:
    """Persist a keyset generated by ``generate_keyset()`` to the database.

    Args:
        db:           Async SQLAlchemy session.
        keyset_data:  Dict as returned by ``cashu_mint.nuts.keyset.generate_keyset()``.

    Returns:
        The persisted ``Keyset`` ORM instance.
    """
    keyset = Keyset(
        id=keyset_data["id"],
        unit=keyset_data["unit"],
        active=keyset_data["active"],
        input_fee_ppk=keyset_data["input_fee_ppk"],
    )
    db.add(keyset)

    for amount, key_pair in keyset_data["keys"].items():
        db.add(
            KeysetKey(
                keyset_id=keyset_data["id"],
                amount=amount,
                private_key=key_pair["private"],
            )
        )

    await db.commit()
    await db.refresh(keyset)
    return keyset


async def deactivate_keyset(db: AsyncSession, keyset_id: str) -> None:
    """Mark a keyset as inactive (e.g., during rotation)."""
    keyset = await get_keyset_by_id(db, keyset_id)
    if keyset:
        keyset.active = False
        await db.commit()
