"""initial_schema

Revision ID: 66a7889ab3e3
Revises: 
Create Date: 2026-02-28 17:56:52.530624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a7889ab3e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyset_keys',
    sa.Column('keyset_id', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('private_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('keyset_id', 'amount')
    )
    op.create_table('keysets',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('input_fee_ppk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('melt_quotes',
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('fee_reserve', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('payment_preimage', sa.String(length=64), nullable=True),
    sa.Column('change', sa.Text(), nullable=True),
    sa.Column('expiry', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('quote_id')
    )
    op.create_table('mint_quotes',
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('expiry', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('quote_id')
    )
    op.create_table('proofs',
    sa.Column('Y', sa.String(length=66), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('keyset_id', sa.String(length=16), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('C', sa.String(length=66), nullable=False),
    sa.Column('witness', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('Y')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proofs')
    op.drop_table('mint_quotes')
    op.drop_table('melt_quotes')
    op.drop_table('keysets')
    op.drop_table('keyset_keys')
    # ### end Alembic commands ###
